; Listing generated by Microsoft (R) Optimizing Compiler Version 19.38.33130.0

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	classify
; Function compile flags: /Odtp
_TEXT	SEGMENT
value$ = 8
classify PROC
; File C:\work\main.c
; Line 4
	mov	DWORD PTR [rsp+8], ecx
; Line 5
	cmp	DWORD PTR value$[rsp], 10
	jle	SHORT $LN2@classify
; Line 6
	mov	eax, DWORD PTR value$[rsp]
	jmp	SHORT $LN3@classify
$LN2@classify:
; Line 8
	mov	eax, DWORD PTR value$[rsp]
	neg	eax
$LN3@classify:
; Line 9
	ret	0
classify ENDP
_TEXT	ENDS
END
