/**
 * Generates the offline CIL instruction documentation table used by the
 * extension. The input is the Markdown transcription of ECMA-335, 6th edition:
 * https://github.com/stakx/ecma-335/tree/f181e4696eebcbbc7c2b1e5d0a2ee289f2884d2d/docs
 *
 * Usage:
 *   node --import tsx scripts/docenizer-dotnet-il.ts <ecma-335-checkout>/docs \
 *     src/artifact-document/generated/dotnet-il-opcodes.ts
 */

import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { format, resolveConfig } from 'prettier';

const specificationRevision = 'f181e4696eebcbbc7c2b1e5d0a2ee289f2884d2d';
const specificationUrl = `https://github.com/stakx/ecma-335/blob/${specificationRevision}/docs`;

interface InstructionInfo {
	readonly tooltip: string;
	readonly html: string;
	readonly url: string;
}

async function main(): Promise<void> {
	const [inputDirectory, outputPath] = process.argv.slice(2);
	if (!inputDirectory || !outputPath) {
		throw new Error('Usage: docenizer-dotnet-il.ts <ecma-335-docs-directory> <output-path>');
	}
	const fileNames = (await readdir(inputDirectory))
		.filter((name) => /^iii\.[234]\.\d+-.+\.md$/u.test(name))
		.sort((left, right) => left.localeCompare(right, 'en'));
	const instructions = new Map<string, InstructionInfo>();
	for (const fileName of fileNames) {
		const source = await readFile(path.join(inputDirectory, fileName), 'utf8');
		for (const [mnemonic, description] of instructionsFrom(source)) {
			const information = {
				tooltip: description,
				html: `<p>${escapeHtml(description)}</p>`,
				url: `${specificationUrl}/${fileName}`,
			};
			// ECMA-335 lists case-preserving assembler aliases (for example,
			// ldc.i4.M1) beside their canonical spellings. Lookup is
			// case-insensitive, so retain the first, canonical table entry.
			if (!instructions.has(mnemonic)) {
				instructions.set(mnemonic, information);
			}
		}
	}
	if (instructions.size === 0) {
		throw new Error('No CIL instructions were found in the supplied ECMA-335 documentation.');
	}
	const output = [
		'// Generated by scripts/docenizer-dotnet-il.ts. Do not edit directly.',
		'// Source: ECMA-335, 6th edition, Partition III (CIL Instruction Set).',
		'',
		'export interface DotNetIlOpcodeDocumentation {',
		'\treadonly tooltip: string;',
		'\treadonly html: string;',
		'\treadonly url: string;',
		'}',
		'',
		`const instructions: Readonly<Record<string, DotNetIlOpcodeDocumentation>> = ${JSON.stringify(
			Object.fromEntries([...instructions.entries()].sort(([left], [right]) => left.localeCompare(right, 'en'))),
			null,
			'\t',
		)};`,
		'',
		'export function documentationForDotNetIlOpcode(',
		'\topcode: string | undefined,',
		'): DotNetIlOpcodeDocumentation | undefined {',
		'\treturn opcode ? instructions[opcode.toLowerCase()] : undefined;',
		'}',
		'',
	].join('\n');
	const formatterOptions = await resolveConfig(path.join(process.cwd(), 'prettier.config.mjs'));
	await writeFile(outputPath, await format(output, { ...formatterOptions, filepath: outputPath }));
	console.log(`Wrote ${instructions.size} CIL opcode entries to ${outputPath}`);
}

function instructionsFrom(source: string): readonly (readonly [string, string])[] {
	const result: Array<readonly [string, string]> = [];
	for (const line of source.split(/\r?\n/u)) {
		const cells = line.split('|').map((cell) => cell.trim());
		const assemblyFormatIndex = cells.findIndex((cell) => /^`[a-z]/iu.test(cell));
		if (assemblyFormatIndex === -1) {
			continue;
		}
		const assemblyFormat = /^`([^`]+)`/u.exec(cells[assemblyFormatIndex])?.[1];
		const description = cells[assemblyFormatIndex + 1];
		const mnemonic = assemblyFormat?.match(/^[a-z][a-z0-9.]*/iu)?.[0]?.toLowerCase();
		if (mnemonic && description) {
			result.push([mnemonic, plainText(description)]);
		}
	}
	return result;
}

function plainText(markdown: string): string {
	return markdown
		.replace(/`([^`]+)`/gu, '$1')
		.replace(/[*_]+/gu, '')
		.replace(/&ndash;/gu, '–')
		.replace(/&hellip;/gu, '…')
		.replace(/\[(.*?)\]\([^)]*\)/gu, '$1')
		.replace(/\s+/gu, ' ')
		.trim();
}

function escapeHtml(value: string): string {
	return value.replace(/[&<>"']/gu, (character) => {
		return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character] ?? character;
	});
}

void main();
